name: Artifact Example

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate file
        run: python my_app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-file
          path: results/output.txt