name: Train Model with Inputs

on:
  workflow_dispatch:
    inputs:
      epochs:
        description: "Number of epochs"
        required: true
        default: "5"

      model:
        description: "Model type"
        required: true
        default: "linear"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run training script
        run: |
          python main_app.py \
          --epochs ${{ github.event.inputs.epochs }} \
          --model ${{ github.event.inputs.model }}